
apiVersion: apps/v1

kind: Deployment

metadata:

      name: rogerdev-titanic-test-backend-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      app: rogerdev-titanic-test-backend

  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: rogerdev-titanic-test-backend

    spec:

      containers:

      - name: rogerdev-titanic-test-backend

        image: mawan1122/rogerdev-titanic-test-backend:latest

        envFrom:

          - secretRef:

              name: rogerdev-titanic-test-db-secret

        ports:

           - containerPort: 8081
---

apiVersion: v1

kind: Service

metadata:

  name: rogerdev-titanic-test-backend-service

spec:

  selector:

    app: rogerdev-titanic-test-backend

  ports:

    - port: 8080

      targetPort: 8081
 
---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: rogerdev-titanic-test-backend-ingress

  annotations:

      nginx.ingress.kubernetes.io/rewrite-target: /
spec:

  rules:

    - host: rogerdev.mawan.info

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:

                name: rogerdev-titanic-test-backend-service
                port:

                  number: 8080
          